// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD98-xpTrja_jxL562bqbIwn8p0wTCR8rE',
    appId: '1:1070125448741:web:e56f58e7572bc4cb4cc9cc',
    messagingSenderId: '1070125448741',
    projectId: 'imperia-hubx',
    authDomain: 'imperia-hubx.firebaseapp.com',
    storageBucket: 'imperia-hubx.appspot.com',
    measurementId: 'G-650TRQ7N0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxthjW0hhxXRgh7iaEMRs8esYY5E4bo2w',
    appId: '1:1070125448741:android:f0ab316313e198324cc9cc',
    messagingSenderId: '1070125448741',
    projectId: 'imperia-hubx',
    storageBucket: 'imperia-hubx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoHIAxxBIXwXT7JaujM19MJw6AuZ4Dom4',
    appId: '1:1070125448741:ios:8fe7114f398ac11b4cc9cc',
    messagingSenderId: '1070125448741',
    projectId: 'imperia-hubx',
    storageBucket: 'imperia-hubx.appspot.com',
    iosClientId: '1070125448741-14bnj50o2ulvm04b0bnekl0sk226sar0.apps.googleusercontent.com',
    iosBundleId: 'in.creativelizard.imperiaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoHIAxxBIXwXT7JaujM19MJw6AuZ4Dom4',
    appId: '1:1070125448741:ios:8fe7114f398ac11b4cc9cc',
    messagingSenderId: '1070125448741',
    projectId: 'imperia-hubx',
    storageBucket: 'imperia-hubx.appspot.com',
    iosClientId: '1070125448741-14bnj50o2ulvm04b0bnekl0sk226sar0.apps.googleusercontent.com',
    iosBundleId: 'in.creativelizard.imperiaHub',
  );
}
